@echo off
echo Initializing Git repository...
git init
echo Adding files to staging area...
git add .
echo Creating initial commit...
git commit -m "Initial commit: Set up Social Media API with user authentication"
echo Adding remote repository...
git remote add origin https://github.com/polymathuniversata/Alx_DjangoLearnLab.git
echo Pushing to GitHub...
git branch -M main
git push -u origin main
pause
