# Generated by Django 5.0.14 on 2025-08-22 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_customuser_following_customuser_followers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="followers",
        ),
        migrations.AddField(
            model_name="customuser",
            name="following",
            field=models.ManyToManyField(
                blank=True,
                related_name="followers",
                through="accounts.UserFollowing",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userfollowing",
            name="following_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_followers_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userfollowing",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_following_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
