# Generated by Django 5.0.14 on 2025-08-22 09:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_customuser_followers_customuser_following_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="following",
        ),
        migrations.AddField(
            model_name="customuser",
            name="followers",
            field=models.ManyToManyField(
                blank=True,
                related_name="following",
                through="accounts.UserFollowing",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
