# Generated by Django 5.0.14 on 2025-08-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
