version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: ${{ PORT }}
      DATABASE_URL: ${{ DATABASE_URL }}
      SECRET_KEY: ${{ SECRET_KEY }}
      DEBUG: False
      ALLOWED_HOSTS: ${{ RAILWAY_STATIC_URL }},${{ RAILWAY_PUBLIC_DOMAIN }}
    ports:
      - "${PORT}:${PORT}"
